name: Dockerize

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - 
      name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - 
      name: Upload .jar File
      uses: actions/upload-artifact@v3
      with:
        name: jar-file
        path: build/libs/sticker-maker-0.0.1.jar
        
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Download .jar File
      uses: actions/download-artifact@v3
      with:
        name: jar-file
    -
      name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sticker-maker:${{ github.run_id }} , ${{ secrets.DOCKER_HUB_USERNAME }}/sticker-maker:latest
