name: Dockerize

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Download .jar File
      uses: actions/download-artifact@v3
      with:
        name: jar-file
    -
      name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sticker-maker:${{ github.run_id }} , ${{ secrets.DOCKER_HUB_USERNAME }}/sticker-maker:latest
